(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(auto-revert-avoid-polling t)
 '(auto-revert-check-vc-info t)
 '(auto-revert-stop-on-user-input nil)
 '(auto-save-list-file-prefix "~/.emacs.d/autosave/")
 '(backup-by-copying t)
 '(backup-directory-alist '(("." . "~/.emacs.d/backup/")))
 '(cider-repl-display-help-banner nil)
 '(cider-repl-pop-to-buffer-on-connect 'display-only)
 '(column-number-mode t)
 '(comint-buffer-maximum-size 2048)
 '(comint-prompt-read-only t)
 '(comment-multi-line t)
 '(compilation-always-kill t)
 '(compilation-ask-about-save nil)
 '(compilation-scroll-output 'first-error)
 '(confirm-nonexistent-file-or-buffer nil)
 '(consult-narrow-key "<")
 '(context-menu-mode t)
 '(copy-region-blink-delay 0)
 '(create-lockfiles nil)
 '(custom-enabled-themes '(modus-operandi-tinted))
 '(custom-safe-themes
   '("712dda0818312c175a60d94ba676b404fc815f8c7e6c080c9b4061596c60a1db" default))
 '(delete-by-moving-to-trash t)
 '(delete-old-versions t)
 '(dired-auto-revert-buffer t)
 '(dired-dwim-target t)
 '(dired-listing-switches "-aFGhlv --group-directories-first")
 '(dired-recursive-copies 'always)
 '(dired-recursive-deletes 'always)
 '(dired-use-ls-dired t)
 '(ediff-split-window-function 'split-window-sensibly)
 '(eglot-connect-timeout 300)
 '(eglot-events-buffer-size 0)
 '(eglot-extend-to-xref t)
 '(eldoc-documentation-strategy 'eldoc-documentation-compose-eagerly)
 '(enable-recursive-minibuffers t)
 '(fast-but-imprecise-scrolling t)
 '(fill-column 80)
 '(find-file-suppress-same-file-warnings t)
 '(find-file-visit-truename t)
 '(frame-inhibit-implied-resize nil)
 '(frame-resize-pixelwise t)
 '(global-auto-revert-non-file-buffers t)
 '(grep-find-command '("rg -n -H --no-heading --glob='' -e ''" . 37))
 '(history-length 300)
 '(hscroll-margin 2)
 '(hscroll-step 1)
 '(idle-update-delay 1.0)
 '(ido-enable-flex-matching nil)
 '(ido-everywhere nil)
 '(indent-tabs-mode nil)
 '(inferior-lisp-program "/usr/bin/sbcl")
 '(inhibit-startup-screen t)
 '(isearch-allow-motion t)
 '(isearch-allow-scroll 'unlimited)
 '(isearch-lazy-count t)
 '(isearch-wrap-pause 'no)
 '(kept-new-versions 5)
 '(kept-old-versions 5)
 '(kill-buffer-delete-auto-save-files t)
 '(kill-do-not-save-duplicates t)
 '(lua-indent-level 2)
 '(lua-indent-nested-block-content-align t)
 '(lua-ts-indent-offset 2)
 '(magit-diff-refine-hunk 'all)
 '(magit-display-buffer-function 'magit-display-buffer-same-window-except-diff-v1)
 '(magit-log-margin '(t "%Y-%m-%d %H:%M " magit-log-margin-width t 18))
 '(major-mode-remap-alist '((janet-mode . janet-ts-mode)))
 '(make-backup-files nil)
 '(minibuffer-prompt-properties '(read-only t cursor-intangible t face minibuffer-prompt))
 '(mode-line-compact 'long)
 '(modus-themes-mixed-fonts t)
 '(mouse-wheel-flip-direction nil)
 '(mouse-wheel-scroll-amount '(1 ((shift) . hscroll)))
 '(mouse-wheel-tilt-scroll t)
 '(mouse-yank-at-point t)
 '(native-comp-async-report-warnings-errors nil)
 '(org-special-ctrl-a/e 'reversed)
 '(package-archive-priorities
   '(("gnu" . 99)
     ("nongnu" . 80)
     ("stable" . 70)
     ("melpa" . 0)))
 '(package-archives
   '(("melpa" . "https://melpa.org/packages/")
     ("gnu" . "https://elpa.gnu.org/packages/")
     ("nongnu" . "https://elpa.nongnu.org/nongnu/")))
 '(package-selected-packages
   '(nerd-icons nerd-icons-completion nerd-icons-corfu nerd-icons-dired dired-subtree odin-mode csv-mode eglot-booster tb-keycast jinx eat marginalia cape embark-consult consult avy standard-themes lua-ts-mode corfu rainbow-mode a-janet-spork-client ajrepl cider clojure-mode dumb-jump eglot elixir-mode embark exec-path-from-shell fennel-mode glsl-mode iedit janet-ts-mode jarchive keychain-environment lua-mode magit mlscroll modus-themes orderless sly vertico which-key yaml-mode zig-mode))
 '(package-vc-selected-packages
   '((odin-mode :vc-backend Git :url "https://git.sr.ht/~mgmarlow/odin-mode")
     (ajrepl :vc-backend Git :url "https://github.com/sogaiu/ajrepl.git")
     (janet-ts-mode :vc-backend Git :url "https://github.com/sogaiu/janet-ts-mode.git")
     (eglot-booster :vc-backend Git :url "https://github.com/jdtsmith/eglot-booster")
     (tb-keycast :vc-backend Git :url "https://github.com/ir33k/tb-keycast.git")
     (a-janet-spork-client :url "https://github.com/sogaiu/a-janet-spork-client.git" :vc-backend Git)))
 '(pixel-scroll-precision-mode t)
 '(prog-mode-hook '(toggle-truncate-lines electric-pair-mode))
 '(recentf-max-saved-items 300)
 '(register-preview-delay 0.5)
 '(repeat-mode t)
 '(revert-without-query '("."))
 '(ring-bell-function 'flash-mode-line)
 '(save-place-file "~/.emacs.d/saveplace")
 '(save-place-limit 600)
 '(savehist-save-minibuffer-history t)
 '(scroll-conservatively 10000)
 '(scroll-error-top-bottom t)
 '(scroll-preserve-screen-position t)
 '(scroll-step 1)
 '(search-whitespace-regexp ".*?")
 '(selectrum-mode nil)
 '(show-paren-context-when-offscreen 'overlay)
 '(show-paren-delay 0.1)
 '(show-paren-when-point-in-periphery t)
 '(show-paren-when-point-inside-paren t)
 '(show-trailing-whitespace t)
 '(switch-to-buffer-in-dedicated-window 'pop)
 '(switch-to-buffer-obey-display-actions t)
 '(tab-bar-auto-width nil)
 '(tab-bar-close-button-show nil)
 '(tab-bar-format '(tab-bar-format-tabs tab-bar-separator))
 '(tab-bar-new-tab-choice "*scratch*")
 '(tab-bar-tab-hints t)
 '(tool-bar-mode nil)
 '(tramp-auto-save-directory "~/.emacs.d/tramp-autosave/")
 '(uniquify-buffer-name-style 'forward nil (uniquify))
 '(vc-follow-symlinks t)
 '(version-control t)
 '(warning-suppress-types '((lexical-binding)))
 '(wgrep-auto-save-buffer t)
 '(windmove-default-keybindings '([ignore] control))
 '(window-divider-default-bottom-width 1)
 '(window-divider-default-places t)
 '(window-divider-default-right-width 1)
 '(word-wrap t)
 '(x-stretch-cursor t)
 '(x-underline-at-descent-line nil)
 '(xref-search-program 'ripgrep)
 '(xref-show-definitions-function 'xref-show-definitions-completing-read))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
